// =================================================================
// CONCORDIA — the orrery of set 07: Orikaia Prime turning in front
// of Orikaia. The renderer is concordia-gl.js (a copy of the Imperial
// Portal's planet shader); this file owns the camera, the turn, the
// drag, the focus switch and the readouts. Nothing loads until the
// set is first on screen: the maps are ~550 KB the rest of the page
// never needs. Without WebGL the Blender renders stand in, still.
// =================================================================
import { createPlanetRenderer } from './concordia-gl.js';

// Generated by build_moonmap.py in gov.inter-astra.net (js/modules/moon-map.js):
// the capital and the aerial photograph's frame on
// Orikaia Prime, in the moon's body frame (x towards 0°E on the equator,
// y north, z towards 90°E).
const MOON_MAP = {"lon0": 139.7, "cap": [35.6, 139.7], "aerial": {"span": 0.012, "w": 1536, "h": 1024, "dome": [740, 432], "east": [-0.64679, 0.0, -0.762668], "north": [0.443967, 0.813101, -0.376511]}};

const MAPS = {
  day: 'images/concordia/orikaia-prime-day.webp',
  data: 'images/concordia/orikaia-prime-data.webp',
  mask: 'images/concordia/seiki-to-mask.webp',
  night: 'images/concordia/orikaia-prime-night.webp',
};

// towards Reika: from the left and behind, so most of the disc is night and the
// cities show their lights; the lit crescent keeps the day in view
const SUN = [-0.9, -0.3, -0.2];
const MOON_DAY_S = 80;     // one turn of the moon, seconds
const GIANT_DAY_S = 55;    // one turn of the giant's cloud deck
// The moon turns about its pole, the pole tipped towards the viewer (TILT)
// and leaning on the screen (ROLL), so the northern seas, Seiki-tō among
// them, turn through the light.
const TILT = -0.38;
const ROLL = 0.22;
const GIANT_TILT = -0.3;   // the giant's equator against the screen
// The system view lights the moons three-quarter on, so the small ones read.
const SUN_SYSTEM = [-0.8, -0.3, 0.4];
// Orikaia's other moons, largest first, sized against Orikaia Prime as the view draws
// it (not to scale: Yūgiri is a few kilometres across). kind: the shader's look.
const SATS = [
  { name: 'Kagerō', jp: '陽炎', kind: 1, size: 0.62 },
  { name: 'Kasumi', jp: '霞', kind: 2, size: 0.55 },
  { name: 'Tsukiyo', jp: '月夜', kind: 0, size: 0.5 },
  { name: 'Yūgiri', jp: '夕霧', kind: 3, size: 0.17 },
];

const norm3 = (v) => { const l = Math.hypot(...v); return v.map((x) => x / l); };
const dot3 = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
const cross3 = (a, b) => [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]];
const unitLL = (lat, lon) => {
  const la = (lat * Math.PI) / 180, lo = (lon * Math.PI) / 180;
  return [Math.cos(la) * Math.cos(lo), Math.sin(la), Math.cos(la) * Math.sin(lo)];
};
// 3 × 3 matrices as row arrays
const mul = (A, B) => A.map((r) => [0, 1, 2].map((j) => r[0] * B[0][j] + r[1] * B[1][j] + r[2] * B[2][j]));
const apply = (M, v) => M.map((r) => r[0] * v[0] + r[1] * v[1] + r[2] * v[2]);
const rotX = (a) => { const c = Math.cos(a), s = Math.sin(a); return [[1, 0, 0], [0, c, -s], [0, s, c]]; };
const rotZ = (a) => { const c = Math.cos(a), s = Math.sin(a); return [[c, -s, 0], [s, c, 0], [0, 0, 1]]; };
// a turn about the view's vertical; the moon's spin, once ALIGN has stood its pole up
const rotY = (a) => { const c = Math.cos(a), s = Math.sin(a); return [[c, 0, -s], [0, 1, 0], [s, 0, c]]; };
const CAP_B = unitLL(...MOON_MAP.cap);
const POLE_B = [0, 1, 0];

// body → view at rest: the pole up the screen,
// Seiki-tō's meridian facing the viewer
const ALIGN = (() => {
  const a = POLE_B;
  const b = norm3(CAP_B.map((x, i) => x - a[i] * dot3(CAP_B, a)));
  const c = cross3(a, b);
  const A = [0, -1, 0], B = [0, 0, 1], C = cross3(A, B);
  return [0, 1, 2].map((j) => [0, 1, 2].map((k) => A[j] * a[k] + B[j] * b[k] + C[j] * c[k]));
})();
const FRAME = {
  lon0: (MOON_MAP.lon0 * Math.PI) / 180,
  capB: CAP_B,
  aerE: MOON_MAP.aerial.east,
  aerN: MOON_MAP.aerial.north,
  aerial: [MOON_MAP.aerial.span, MOON_MAP.aerial.dome[0] / MOON_MAP.aerial.w, MOON_MAP.aerial.dome[1] / MOON_MAP.aerial.h],
};

// Where each body stands for each focus, as fractions of the stage. Wide
// stages keep the left for the title; narrow ones stack and centre. Outside the
// system view the other moons wait stacked behind the homeworld, out of sight.
const behind = (moon) => SATS.map((m) => [moon[0], moon[1], moon[2] * m.size * 0.9]);

// The system view: Orikaia at the back, the moons in front on an arc round a pivot
// below the stage, largest on the left, like a hand of cards.
function fan(w, h) {
  const gr = Math.min(h * 0.28, w * 0.18);
  const base = Math.min(h * 0.14, w * 0.08);
  // a flat arc: its middle at 58 % of the height, its ends not much lower
  const R = h * 1.9;
  const pivot = [w * 0.5, h * 0.58 + R];
  const span = Math.asin(Math.min(0.92, (w * 0.39) / R));
  const n = SATS.length + 1;
  const angles = Array.from({ length: n }, (_, i) => -span + (2 * span * i) / (n - 1));
  const at = (ang) => [pivot[0] + R * Math.sin(ang), pivot[1] - R * Math.cos(ang)];
  return {
    giant: [w * 0.5, h * 0.3, gr],
    prime: [...at(angles[0]), base * 1.25],
    radii: SATS.map((m) => base * 1.25 * m.size),
    angles, at,
  };
}

function layout(focus, w, h) {
  const m = Math.min(w, h);
  const wide = w / h > 1.15;
  if (focus === 'system') {
    const F = fan(w, h);
    return {
      mode: 'system', sun: 1, giant: F.giant, moon: F.prime, fan: F,
      sats: SATS.map((_, i) => [...F.at(F.angles[i + 1]), F.radii[i]]),
    };
  }
  if (focus === 'giant') {
    const gr = Math.min(h * 0.36, w * (wide ? 0.17 : 0.2));
    const moon = [w * (wide ? 0.66 : 0.5) + gr * 1.05, h * 0.5 + gr * 0.62, m * 0.055];
    return { mode: 'giant', sun: 0, giant: [w * (wide ? 0.66 : 0.5), h * 0.5, gr], moon, sats: behind(moon) };
  }
  // the halo reaches 1.2 radii: sized so it never leaves the stage
  const mr = wide ? Math.min(h * 0.36, w * 0.24) : m * 0.36;
  const mc = [w * (wide ? 0.66 : 0.5), h * 0.5];
  const moon = [mc[0], mc[1], mr];
  return {
    mode: 'prime', sun: 0, moon,
    // behind the moon's shoulder, high and to the right, its lit limb towards the star
    giant: [mc[0] + mr * 1.15, mc[1] - mr * 1.25, mr * 1.3],
    sats: behind(moon),
  };
}

function init() {
  const box = document.getElementById('orrery');
  const stage = document.getElementById('orreryStage');
  const canvas = document.getElementById('orreryGl');
  if (!box || !stage || !canvas) return;
  // wait for the first sight of the set (set-mode keeps it display:none till then)
  const io = new IntersectionObserver(([e]) => {
    if (!e.isIntersecting) return;
    io.disconnect();
    start(box, stage, canvas);
  }, { rootMargin: '200px 0px' });
  io.observe(stage);
}

function start(box, stage, canvas) {
  const lite = !!window.LUCYA_LITE;
  const still = lite || window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  const capTag = document.getElementById('tagCap');
  const moonTag = document.getElementById('tagMoon');
  const giantTag = document.getElementById('tagGiant');
  const clock = document.getElementById('capClock');
  const phase = document.getElementById('capPhase');
  const tabs = Array.from(box.querySelectorAll('[data-focus]'));
  const sheets = Array.from(box.querySelectorAll('[data-sheet]'));

  // the stars: drawn once per size, seeded so they hold still across resizes
  const starCanvas = document.getElementById('orreryStars');
  const drawStars = () => {
    if (!starCanvas) return;
    const r = stage.getBoundingClientRect();
    if (!r.width || !r.height) return;
    const k = Math.min(window.devicePixelRatio || 1, 2);
    starCanvas.width = Math.round(r.width * k);
    starCanvas.height = Math.round(r.height * k);
    const ctx = starCanvas.getContext('2d');
    let seed = 2847;
    const rnd = () => ((seed = (seed * 16807) % 2147483647) / 2147483647);
    const n = Math.round((r.width * r.height) / 1400);
    for (let i = 0; i < n; i++) {
      const x = rnd() * starCanvas.width, y = rnd() * starCanvas.height;
      const m = Math.pow(rnd(), 3);
      const warm = rnd();
      ctx.globalAlpha = 0.25 + m * 0.75;
      ctx.fillStyle = warm > 0.85 ? '#ffe2b8' : warm < 0.2 ? '#b8ccff' : '#ffffff';
      ctx.fillRect(x, y, (0.6 + m * 1.6) * k, (0.6 + m * 1.6) * k);
    }
    ctx.globalAlpha = 1;
  };

  let planet = null;
  try { planet = createPlanetRenderer(canvas, MAPS, () => box.classList.add('is-ready')); } catch (_) { planet = null; }
  if (!planet) {
    box.classList.add('is-fallback');
    stage.querySelectorAll('img[data-src]').forEach((img) => { img.src = img.dataset.src; });
    drawStars();
    new ResizeObserver(drawStars).observe(stage);
    return;
  }

  let W = 0, H = 0;
  let dpr = Math.min(window.devicePixelRatio || 1, lite ? 1 : 1.5);
  const resize = () => {
    const r = stage.getBoundingClientRect();
    if (!r.width || !r.height) return;   // the set is hidden: keep the last size
    W = r.width; H = r.height;
    planet.resize(W, H, dpr);
    drawStars();
    dirty = true;
  };

  // the turn, and what the visitor adds to it by dragging
  let spin = 2.4;          // radians: Seiki-tō starts on the morning side, about to cross
  let gspin = 0;
  let satSpin = 0;
  let focus = 'prime';
  let from = null, to = null, tweenT = 1;
  let dirty = true;

  const setFocus = (f) => {
    if (f === focus) return;
    from = current();
    focus = f;
    tweenT = 0;
    tabs.forEach((t) => t.setAttribute('aria-pressed', String(t.dataset.focus === f)));
    sheets.forEach((s) => { s.hidden = s.dataset.sheet !== f; });
    box.dataset.focus = f;
    dirty = true;
  };
  tabs.forEach((t) => t.addEventListener('click', () => setFocus(t.dataset.focus)));

  const ease = (x) => 1 - Math.pow(1 - x, 3);
  const lerp = (a, b, k) => a.map((x, i) => x + (b[i] - x) * k);
  const clamp01 = (x) => Math.max(0, Math.min(1, x));
  function current() {
    to = layout(focus, W, H);
    if (!from || tweenT >= 1) return { ...to, open: to.mode === 'system' ? SATS.map(() => 1) : SATS.map(() => 0) };
    const t = tweenT;
    if (to.mode === 'system' && from.mode !== 'system') {
      const k = ease(clamp01(t / 0.5));
      const moon = lerp(from.moon, to.moon, k), giant = lerp(from.giant, to.giant, k);
      const F = to.fan;
      const open = SATS.map((_, i) => ease(clamp01((t - 0.42 - i * 0.08) / 0.42)));
      const sats = SATS.map((_, i) => open[i] > 0
        ? [...F.at(F.angles[0] + (F.angles[i + 1] - F.angles[0]) * open[i]), F.radii[i]]
        : [moon[0], moon[1], moon[2] * SATS[i].size * 0.9]);
      return { mode: 'system', sun: k, moon, giant, sats, open, fan: F };
    }
    if (from.mode === 'system' && to.mode !== 'system') {
      const F = from.fan;
      const shut = SATS.map((_, i) => ease(clamp01((t - (SATS.length - 1 - i) * 0.06) / 0.38)));
      const k = ease(clamp01((t - 0.45) / 0.55));
      const moon = lerp(from.moon, to.moon, k), giant = lerp(from.giant, to.giant, k);
      const sats = SATS.map((_, i) => shut[i] < 1
        ? [...F.at(F.angles[i + 1] + (F.angles[0] - F.angles[i + 1]) * shut[i]), F.radii[i]]
        : [moon[0], moon[1], moon[2] * SATS[i].size * 0.9]);
      return { mode: to.mode, sun: 1 - k, moon, giant, sats, open: shut.map((x) => 1 - x), fan: F };
    }
    const k = ease(t);
    return {
      mode: to.mode, sun: to.sun, moon: lerp(from.moon, to.moon, k), giant: lerp(from.giant, to.giant, k),
      sats: SATS.map((_, i) => lerp(from.sats[i], to.sats[i], k)), open: SATS.map(() => 0),
    };
  }

  // drag: sideways turns the body in focus, about its own pole
  let drag = null;
  stage.addEventListener('pointerdown', (e) => {
    if (e.target.closest('button, a')) return;
    drag = { x: e.clientX, y: e.clientY, id: e.pointerId };
    stage.setPointerCapture(e.pointerId);
    stage.classList.add('is-dragging');
  });
  stage.addEventListener('pointermove', (e) => {
    if (!drag || e.pointerId !== drag.id) return;
    const dx = e.clientX - drag.x;
    drag.x = e.clientX;
    const r = Math.max((current()[focus === 'giant' ? 'giant' : 'moon'][2]), 60);
    if (focus === 'giant') gspin -= dx / r;
    else {
      spin += dx / r;
    }
    dirty = true;
  });
  const endDrag = () => { drag = null; stage.classList.remove('is-dragging'); };
  stage.addEventListener('pointerup', endDrag);
  stage.addEventListener('pointercancel', endDrag);

  const placeTag = (el, x, y, show) => {
    if (!el) return;
    // keep the plain labels on the stage; the capital's pin has to sit on its spot
    if (el !== capTag) x = Math.max(12, Math.min(x, W - el.offsetWidth - 12));
    el.style.transform = `translate(${x.toFixed(1)}px, ${y.toFixed(1)}px)`;
    el.classList.toggle('is-off', !show);
  };

  const satTags = SATS.map((_, i) => document.getElementById(`tagSat${i}`));
  let lastClock = '';
  function frame() {
    const L = current();
    const sun = norm3(lerp(SUN, SUN_SYSTEM, L.sun));
    // the spin runs in view space about the stood-up axis; negative carries the near side rightwards
    const toView = mul(rotZ(ROLL), mul(rotX(TILT), mul(rotY(-spin), ALIGN)));
    // view → body is the transpose; the shader wants it column-major, which is
    // toView's rows laid end to end
    const toBody = toView.flat();
    const v = (b) => norm3(apply(toView, b));
    const pole = v([0, 1, 0]);
    const capV = v(CAP_B);

    planet.draw({
      moon: [L.moon[0] * dpr, L.moon[1] * dpr, L.moon[2] * dpr],
      giant: [L.giant[0] * dpr, L.giant[1] * dpr, L.giant[2] * dpr],
      tilt: GIANT_TILT, spin: gspin, sun, alpha: 1, dpr,
      toBody, frame: FRAME,
      sats: L.sats.map((m, i) => [m[0] * dpr, m[1] * dpr, m[2] * dpr, SATS[i].kind]),
      satSpin,
    });
    L.sats.forEach((m, i) => placeTag(satTags[i], m[0] - 30, m[1] + m[2] + 10, L.open[i] > 0.92));

    // Seiki-tō: where it shows, and its hour by the star
    placeTag(capTag, L.moon[0] + capV[0] * L.moon[2], L.moon[1] + capV[1] * L.moon[2], capV[2] > 0.18 && L.moon[2] > 80);
    if (L.mode === 'system') placeTag(moonTag, L.moon[0] - 50, L.moon[1] + L.moon[2] + 10, true);
    else placeTag(moonTag, L.moon[0] + L.moon[2] * 0.72, L.moon[1] + L.moon[2] * 0.98, true);
    placeTag(giantTag, L.giant[0] + L.giant[2] * 0.2, L.giant[1] - L.giant[2] * 1.02, L.giant[1] - L.giant[2] * 1.02 > 24);
    const flat = (x) => norm3(x.map((c, i) => c - pole[i] * dot3(x, pole)));
    const s0 = flat(sun), c0 = flat(capV);
    const ha = Math.atan2(dot3(c0, cross3(s0, pole)), dot3(c0, s0));
    const hours = (((12 + (ha * 12) / Math.PI) % 24) + 24) % 24;
    const hh = Math.floor(hours), mm = Math.floor((hours - hh) * 60);
    const text = `${String(hh).padStart(2, '0')}:${String(mm).padStart(2, '0')}`;
    if (text !== lastClock && clock) {
      lastClock = text;
      clock.textContent = text;
      const elev = dot3(capV, sun);
      if (phase) phase.textContent = elev > 0.1 ? 'DAY · 昼' : elev > -0.1 ? (hours < 12 ? 'DAWN · 暁' : 'DUSK · 夕') : 'NIGHT · 夜';
    }
  }

  // run only while the stage is on screen and the tab is visible
  let visible = true, raf = 0, last = 0;
  let slow = 0;
  const tick = (now) => {
    raf = 0;
    const dt = last ? Math.min((now - last) / 1000, 0.1) : 0;
    last = now;
    if (!still && !drag) {
      spin += (dt * 2 * Math.PI) / MOON_DAY_S;
      gspin += (dt * 2 * Math.PI) / GIANT_DAY_S;
      satSpin += dt * 0.25;
      dirty = true;
    }
    if (tweenT < 1) {
      const span = (focus === 'system' || (from && from.mode === 'system')) ? 1.9 : 1.1;
      tweenT = Math.min(1, tweenT + dt / span);
      dirty = true;
    }
    if (dirty && W) {
      const t0 = performance.now();
      frame();
      dirty = false;
      // a slow GPU gets fewer pixels rather than a stutter
      if (dt > 0 && performance.now() - t0 + dt * 1000 > 34) slow++; else slow = Math.max(0, slow - 1);
      if (slow > 40 && dpr > 0.75) { dpr = Math.max(0.75, dpr - 0.25); slow = 0; resize(); }
    }
    if (visible && !document.hidden) raf = requestAnimationFrame(tick);
  };
  const wake = () => { if (!raf && visible && !document.hidden) { last = 0; raf = requestAnimationFrame(tick); } };

  new ResizeObserver(() => { resize(); wake(); }).observe(stage);
  new IntersectionObserver(([e]) => { visible = e.isIntersecting; wake(); }).observe(stage);
  document.addEventListener('visibilitychange', wake);
  stage.addEventListener('pointermove', wake);
  resize();
  wake();
}

if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
else init();
